### ISSUE TITLE
Stream RTSP

### ISSUE THREAD

**Issue by mehta-viru1** [rpetrich/MobileVLC#1]
Hello Petrich,

Will VLC be able to stream video using the RTSP protocol ?
MP4 Video using H.264 Baseline profile.

Thanks for your time,
Viraj

**Comment by rpetrich** [comment]
I don't develop VLC itself, only maintain the VLC port to iPhone.

**Comment by mehta-viru1** [comment]
Can you tell me who is the right person to ask this question ?
